<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
    <PackageOutputPath>$(OneDrive)\NuGet</PackageOutputPath>
    <PackageLicenseExpression>CC0-1.0</PackageLicenseExpression>
    <Title>$(AssemblyName)</Title>
    <Authors>codespirals, Eliterate</Authors>
    <Company>codespirals</Company>
    <NeutralLanguage>en</NeutralLanguage>
    <PackageIcon>logo.png</PackageIcon>
    <Copyright>codespirals</Copyright>
    <PackageProjectUrl>https://www.codespirals.dev/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Codespirals/Codespirals.CardGames/tree/master/Codespirals.CardGames.Poker</RepositoryUrl>
    <PackageTags>codespirals;poker;games;</PackageTags>
    <Version>1.0.7.26122</Version>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="..\..\Codespirals.Base\Codespirals.Base.Shared\Resources\Images\logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Helpers\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Codespirals.CardGames.Shared" Version="1.0.0.26120" />
  </ItemGroup>
  <ItemGroup>
    <None Update="AutoUpdateVersionNumber.ps1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="PowerShell -ExecutionPolicy Bypass -NoProfile -File AutoUpdateVersionNumber.ps1" />
  </Target>
</Project>